# Generated by Django 4.0 on 2022-07-02 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=440)),
                ('website', models.CharField(blank=True, max_length=250)),
                ('desc', models.TextField(blank=True)),
                ('thumb_img', models.ImageField(blank=True, upload_to='thumb')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_apps', to='users.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='LargeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_large_images', to='apps_app.appproduct')),
            ],
        ),
        migrations.AddField(
            model_name='appproduct',
            name='category',
            field=models.ManyToManyField(related_name='all_apps', to='apps_app.Category'),
        ),
    ]
