# Generated by Django 4.0 on 2022-07-02 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
