# Generated by Django 4.0 on 2022-07-02 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='ac',
            new_name='user_ac',
        ),
    ]
